In [1]:
import numpy as np
import time 

In [2]:
# Adding Two Lists VS. Numpy Arrays.

# python List.
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
result = [x+y for x,y in zip(list1,list2)]
end = time.time()
print("Python list Time:",end-start)

# Numpy Arrays.

arr1 = np.array(list1)
arr2 = np.array(list2)

start = time.time()
result = arr1 + arr2
end = time.time()
print("Numpy Array Time:",end-start)

Python list Time: 0.14533734321594238
Numpy Array Time: 0.02234816551208496


In [3]:
#Creating a 1D Numpy Arrays. 

arr = np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [4]:
# Creating a 2D Numpy Array.

arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1)
print("shape:",arr1.shape)

[[1 2 3]
 [4 5 6]]
shape: (2, 3)


In [5]:
# Checking type and shape

arr = np.array([1,2,3,4,5,6])
print("type:",arr.dtype)
print("Shape:",arr.shape)

type: int64
Shape: (6,)


In [6]:
# Memory efficieny- Numpys VS. Lists.
import sys 

list_data = list(range(11000))
numpy_data = np.array(list_data)

print("Python list size:",sys.getsizeof(list_data)*len(list_data),"bytes")
print("Nmupy Array size:",numpy_data.nbytes,"bytes")


Python list size: 968616000 bytes
Nmupy Array size: 88000 bytes


In [7]:
# Creating Arrays from Scratch.

arr1 = np.zeros((3,3))
print(arr1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
arr2 = np.ones((4,4))
print(arr2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
arr3 = np.full((3,3),5)
print(arr3)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [10]:
arr4 = np.eye(4)
print(arr4)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
arr5 = np.arange(1,10,2)
print(arr5)

[1 3 5 7 9]


In [12]:
arr6 = np.linspace(0,5,5)
print(arr6)

[0.   1.25 2.5  3.75 5.  ]


In [13]:
# indexing & Slicing. 

In [14]:
# indexing.
arr = np.array([10,20,30,40,50,60])
print(arr)
print(arr[2])
print(arr[0])
print(arr[-1])
print(arr[1])

[10 20 30 40 50 60]
30
10
60
20


In [15]:
# Slicing.
arr = np.array([100,200,300,400,500,600])
print(arr)
print(arr[0:2])
print(arr[::-1])
print(arr[3:5])

[100 200 300 400 500 600]
[100 200]
[600 500 400 300 200 100]
[400 500]


In [16]:
arr = np.array([10,22,30,42,50,61])
print(arr.copy())

[10 22 30 42 50 61]


In [17]:
arr[0] = 12
print(arr)

[12 22 30 42 50 61]


In [18]:
# Fancy indexing 

arr = np.array([10,20,30,40,50,60])
print(arr)
idx = [0,2,1]

print("Print fancy indexing",arr[idx])

[10 20 30 40 50 60]
Print fancy indexing [10 30 20]


In [19]:
# Boolean Masking.

student_marks = np.array([22,32,40,85,98,63,45,12,78])
pass_student = student_marks > 33
print("This data is passing marks",student_marks[pass_student])

This data is passing marks [40 85 98 63 45 78]


In [20]:
# Reshaping 

arr = np.array([1,2,3,4,5,6])
print(arr)
matrix = arr.reshape(2,3)
print(matrix)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [21]:
# Create a 3x3 array filled with random number and print its shape.

arr = np.random.rand(3,3)
print(arr)

[[0.39392187 0.44132157 0.94489111]
 [0.07833555 0.8662789  0.82369574]
 [0.21558962 0.15937123 0.67277506]]


In [22]:
# Convert an array of flots [1.1,2.2,3.3,4.4,5.5] into interger.

arr = np.array([1.1,2.2,3.3,4.4,5.5], dtype="int")
print(arr)

arr = np.array([1.1,2.2,3.3,4.4,5.5])
int_arr = arr.astype(int)
print(int_arr)

[1 2 3 4 5]
[1 2 3 4 5]


In [23]:
# Convert an array of interger [1,2,3,4,5] into float.

arr = np.array([1,2,3,4,5])
float_arr = arr.astype(float)
print(float_arr)

arr = np.array([1,2,3,4,5], dtype="float")
print(arr)

[1. 2. 3. 4. 5.]
[1. 2. 3. 4. 5.]


In [24]:
# use fancy indexing to extract even number from [1,2,3,4,5,6].

arr = np.array([1,2,3,4,5,6])
even_number = [0,1,3,5]
print(arr[even_number])

[1 2 4 6]


In [25]:
# Reshape a 1D array of size 9 into 3x3 matrix.

arr = np.array([1,2,3,4,5,6,7,8,9])
matrix_arr = arr.reshape(3,3)
print(matrix_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
# use boolean masking to filter numbers greater than 50 in an array.

student_score = np.array([12,70,65,30,49,85,95,65,46,23,70,94,52,90])
pass_score = student_score > 50
print(student_score[pass_score])

[70 65 85 95 65 70 94 52 90]


In [27]:
# Multidimensional indexing and Axis in Numpy.

arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

arr1[0] # axis 0 Rows 

[1 2 3 4 5 6 7 8 9]


array([1, 2, 3])

In [28]:
np.sum(arr1, axis=0)  # Sum along rows(Down each column).

array([12, 15, 18])

In [29]:
np.sum(arr1, axis=1)  # sum along columns(arcoss each row).

array([ 6, 15, 24])

In [30]:
# indexing in multidimensional Arrays.

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [31]:
print(arr[0][1])  # Accessing an element.
print(arr[1][0])
print(arr[0:1])

2
4
[[1 2 3]]


In [32]:
# 3D Array.

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [33]:
print(arr[0,0,2])

3


In [34]:
# Selecting Data Along Axes.

# Get all rows of the first column.
arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
first_col = arr[:,0]
print(first_col)

[[1 2 3]
 [7 8 9]]


In [35]:
# Changing Data Along an Axis.

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [36]:
# replace all elements in columns 1 with 0.
arr[:,1]=0
print(arr)

[[[1 2 3]
  [0 0 0]]

 [[7 8 9]
  [0 0 0]]]


In [37]:
# Data Types in Numpy Arrays.  

In [38]:
arr = np.array([1,2,3,4,5,6])
print(arr)
print(arr.dtype)

[1 2 3 4 5 6]
int64


In [54]:
# Changing Data Types.

arr = np.array([1.2,5.3,4.5])
print(arr)
print(arr.dtype)

int_arr = arr.astype("int64")
print(int_arr)
print(int_arr.dtype)

[1.2 5.3 4.5]
float64
[1 5 4]
int64


In [53]:
# Downcasting to save memory.

arr_large = np.array([10000,20000,30000])
print(arr_large)
print(arr_large.dtype)

arr_small = arr_large.astype(np.int32)
print(arr_small)
print(arr_small.dtype)

[10000 20000 30000]
int64
[10000 20000 30000]
int32


In [59]:
# memory usage:- 

arr_int64 = np.array([10,20,30], dtype=np.int64)
arr_int32 = np.array([10,20,30], dtype=np.int32)

print(arr_int64)
print(arr_int64.nbytes)

print(arr_int32)
print(arr_int32.nbytes)

[10 20 30]
24
[10 20 30]
12


In [65]:
# Complex Number in Numpy Arrays.

complex_arr = np.array([1+3j, 2+4j, 3+10j])
print(complex_arr)

# Sum Two number.

arr1 = np.array([1+3j])
arr2 = np.array([2+4j])
print("Sum Two number",arr1 + arr2)

# Sum Three number.

arr1 = np.array([1+3j])
arr2 = np.array([2+4j])
arr3 = np.array([3+10j])
print("Sum Three number",arr1 + arr2 + arr3)

[1. +3.j 2. +4.j 3.+10.j]
Sum Two number [3.+7.j]
Sum Three number [6.+17.j]


In [76]:
# BoardCasting in Numpy Array.

square = np.array([1,2,3,4,5])
print(square)
result = []

for num in square:
    result.append(num**2)
print("Square",result)

[1 2 3 4 5]
Square [np.int64(1), np.int64(4), np.int64(9), np.int64(16), np.int64(25)]


In [78]:
# Vectorized opertion.

arr = np.array([1,2,3,4,5])
square = arr**2
print(square)

[ 1  4  9 16 25]


In [80]:
# BroadCasting: Scling Arrays without extra memory.

arr = np.array([1,2,3,4,5])
print(arr)
result = arr + 10
print(result)

[1 2 3 4 5]
[11 12 13 14 15]


In [81]:
# BoardCasting with Two Arrays.

arr1 = np.array([1,2,3,4])
arr2 = np.array([7,1,2,4])

arr_sum = arr1 + arr2
print(arr_sum)

[8 3 5 8]


In [83]:
# Boardcasting a 2D Array and 1D Array.

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([10,20,30])

result = arr1 + arr2
print(result)

[[11 22 33]
 [14 25 36]]
