In [1]:
import numpy as np
# Creating Numpy array 

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3],[2,3,4]])
print(arr1)
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [2 3 4]]


In [2]:
# Creating Arrays from scratch.

np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [3]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [4]:
np.full((4,5),8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [10]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
# range (start, end , step)
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [8]:
np.linspace(2,5,5)

array([2.  , 2.75, 3.5 , 4.25, 5.  ])