In [3]:
import numpy as np
import time 

# python list
size = 1000
list1 = list(range(size))
list2 = list(range(size))

start = time.time()
result = [x + y for x,y in zip(list1,list2)]
end = time.time()
print("Python list addition time:",end-start)

# Numpy array
arr1 =np.array(list1)
arr2 = np.array(list2)
start = time.time()
result = arr1 + arr2
end = time.time()
print("Numpy array addition time:",end-start)

Python list addition time: 0.00021505355834960938
Numpy array addition time: 0.0023987293243408203


In [2]:
# Creating Numpy Arrays.
import numpy as np

# Creating a 1D Numpy array
arr1 = np.array([1,2,3,4,5,6])
print(arr1)

# Creating a 2D Numpy Array
arr2 = np.array([[1,2,3,4],[4,5,6,4],[1,3,4,8]])
print(arr2)

# Chacking type and Shape
print("Type",type(arr1))
print("Shape",arr2.shape)

[1 2 3 4 5 6]
[[1 2 3 4]
 [4 5 6 4]
 [1 3 4 8]]
Type <class 'numpy.ndarray'>
Shape (3, 4)


In [4]:
# Memory Efficiency - Numpy vs. lists.
import sys 

list_data = list(range(1000))
numpy_data = np.array(list_data)

print("Python list size:", sys.getsizeof(list_data)*len(list_data),"bytes")
print("Numpy array size", numpy_data.nbytes,"bytes")

Python list size: 8056000 bytes
Numpy array size 8000 bytes
