In [1]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr,arr.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [2]:
print(arr[0])

[1 2 3]


In [3]:
# flat arr.flatten() it mean convert 2D & 3D Array the 1D.
flat = arr.flatten()
print(flat)

[1 2 3 4 5 6 7 8 9]


In [4]:
# indexing (same as python Lists)
print(flat[0])
print(flat[2])
print(flat[3])
print(flat[4])

1
3
4
5


In [5]:
# Slicing (Extracting parts of an Array)
arr1 = np.array([10,20,30,40,60,80])

print(arr1[1:4]) 
print(arr1[:3])
print(arr1[::2])
print(arr1[0:4])
print(arr1[1:6])

[20 30 40]
[10 20 30]
[10 30 60]
[10 20 30 40]
[20 30 40 60 80]


In [11]:
b = arr1[0:4].copy()   # This is not a slice because we are using copy method to get the copy.
print(b)

[10 20 30 40]


In [7]:
b[0] = 10000666
print(b)

[10000666       20       30       40]


In [8]:
b = arr1[0:4].copy()
print(b)

[10 20 30 40]


In [9]:
b[1] = 900
b

array([ 10, 900,  30,  40])

In [10]:
b = arr1[0:4].copy()
print(b)

[10 20 30 40]


In [ ]:
# Fancy Indexing (select multiple elements).

In [16]:
arr3 = np.array([1,4,7,8,9,10,12,14])
idx = [2,4,1]
print(arr3[idx])

[7 9 4]


In [ ]:
# Boolean Masking (Filter Data).

In [24]:
arr = np.array([20,25,15,5,10,8,18,30,19,15])
marks = arr > 15
print(arr[marks])

[20 25 18 30 19]
