In [1]:
import numpy as np

In [2]:
# 1. create a 3x3 array filled with random numbers and print its shape.

In [4]:
arr = np.random.rand(3,3)
print(arr)
print(arr.shape)

[[0.0012654  0.1694045  0.34743566]
 [0.9169942  0.38700985 0.83869314]
 [0.24514921 0.8073582  0.36396032]]
(3, 3)


In [5]:
# 2. convert an array of floats [1.1, 2.2, 3.3] into integers.

In [15]:
arr = np.array([1.1, 2.2, 3.3])
int_arr = arr.astype(int)
print(int_arr)

[1 2 3]


In [16]:
arr = np.array([1.1, 2.2, 3.3] , dtype=int)
print(arr)

[1 2 3]


In [17]:
arr = np.array([1, 2, 3], dtype=float)   # convert an array of integers [1,2,3] into float.
print(arr)

[1. 2. 3.]


In [18]:
arr = np.array([1, 2, 3])
float_arr = arr.astype(float)
print(float_arr)

[1. 2. 3.]


In [ ]:
# 3. use fancy indexing to extract even number from [1,2,3,4,5,6]

In [20]:
arr = np.array([1,2,3,4,5,6])
idx = [1,3,5]
print(arr[idx])

[2 4 6]


In [ ]:
# 4. Reshape a 1D array of size 9 into 3x3 matxic.

In [23]:
arr = np.array([1,2,3,4,5,6,7,8,9])
matrix = arr.reshape(3,3)
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# 5. use boolean masking to filter numbers greater than 50 in an array.

In [25]:
arr = np.array([100,25,75,76,20,21,71,60,26,81])
marks = arr > 50
print(arr[marks])

[100  75  76  71  60  81]
