In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[2,3,4],[5,6,7]])

In [3]:
print(arr)

[[1 2 3]
 [2 3 4]
 [5 6 7]]


In [4]:
print(arr[0]) # Add column all [0] index.

[1 2 3]


In [5]:
arr1 = np.array([[1,2,3],[2,3,4],[5,6,7]])
arr = (np.sum(arr1, axis=0))

In [6]:
print(arr)  # all column add index by 

[ 8 11 14]


In [7]:
arr2 = np.array([[1,2,3],[2,3,4],[5,6,7]])
print(np.sum(arr2, axis=1))

[ 6  9 18]


In [8]:
arr3 = np.array([[1,2,3],[2,3,4],[5,6,7]])

In [9]:
print(arr3)

[[1 2 3]
 [2 3 4]
 [5 6 7]]


In [10]:
print(arr3[1,2])  # Row index 1, column index 2

4


In [11]:
print(arr3[0:2, 1:3])  # Extracts first 2 row and last 2 columns

[[2 3]
 [3 4]]


In [12]:
arr3D = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) # 3D Array

In [13]:
print(arr3D)
print(arr3D.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [19]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
matrix = arr.reshape(2,2,3)
print(matrix)
print(arr.shape)
print(arr.dtype)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(12,)
int64


In [15]:
print(arr3D[0,1,2])  # First sheet, second row, third column.

6


In [16]:
print(arr3D[:,0,:])  # Get the first row from both sheets.

[[1 2 3]
 [7 8 9]]


In [17]:
first_col = arr3D[:,0] 
print(first_col)

[[1 2 3]
 [7 8 9]]


In [18]:
# Changing Data along an Axis 
arr3D[:,0] = 0   # Replace all elements in column 1 with 0.
print(arr3D)

[[[ 0  0  0]
  [ 4  5  6]]

 [[ 0  0  0]
  [10 11 12]]]
