In [9]:
import numpy as np
import time

# Numpy VS. Python Lists perfomance Test

# Python list
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))
start = time.time()
result = [x + y for x,y in zip(list1,list2)]
end = time.time()
print("Python list addition time:",end-start)

# Numpy Array
arr1 = np.array(list1)
arr2 = np.array(list2)
start = time.time()
result = arr1 + arr2
end = time.time()
print("Numpy array addition time:",end-start)

Python list addition time: 0.15999507904052734
Numpy array addition time: 0.021299362182617188


In [63]:
# Creating a 1D Numpy Array.
arr = np.array([1,2,3,4,5,6])
print("1D Numpy Array:",arr)
matrix = arr.reshape(2,3)
print("print reshape array:",matrix)

# Creating a 2D Numpy Array.
arr1 = np.array([[10,20,30],[40,70,80]])
print("2D Numpy Array:",arr1)

# Checking type and Shape.
print("Type of arr",type(arr1))
print("Shape of arr",arr1.shape)

1D Numpy Array: [1 2 3 4 5 6]
print reshape array: [[1 2 3]
 [4 5 6]]
2D Numpy Array: [[10 20 30]
 [40 70 80]]
Type of arr <class 'numpy.ndarray'>
Shape of arr (2, 3)


In [22]:
# Memory Efficieny - Numpy VS Python List

import sys

list_data = list(range(1000))
Numpy_data = np.array(list_data)

print("Python list size:",sys.getsizeof(list_data)*len(list_data),"bytes")
print("Numpy araay size:",Numpy_data.nbytes,"bytes")

Python list size: 8056000 bytes
Numpy araay size: 8000 bytes


In [52]:
# Creating Arrays from Scatch.

arr = np.array([1,2,3,4,5,6])
print("Print of Array:",arr)

print("Print 3x3 array of zeros:",np.zeros((3,3)))

print("Print 2x4 array of ones:",np.ones((2,4)))

print("Print 2x2 array filled with 7:",np.full((3,3),7))

print("print arange",np.arange(1,10,2))

print("print evenly spaced",np.linspace(0,1,5))


Print of Array: [1 2 3 4 5 6]
Print 3x3 array of zeros: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Print 2x4 array of ones: [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Print 2x2 array filled with 7: [[7 7 7]
 [7 7 7]
 [7 7 7]]
print arange [1 3 5 7 9]
print evenly spaced [0.   0.25 0.5  0.75 1.  ]


In [81]:
# Indexing & Slicing in Numpy Array.

arr = np.array([10,20,30,40])  

print(arr[0])  #Indexing
print(arr[1])
print(arr[2])
print(arr[3])

# Slicing 

print(arr[0:5]) 
print(arr[0:2])
print(arr[3:4])
print(arr[:3])

# Indexing Negative

print(arr[-2])
print(arr[-4])
print(arr[-1])

# Slicing Negative

print(arr[-2:-1])
print(arr[:-1])


10
20
30
40
[10 20 30 40]
[10 20]
[40]
[10 20 30]
30
10
40
[30]
[10 20 30]


In [103]:
# Fancy Indexing & Bo0lean Masking.

arr = np.array([50,30,25,65,78,39])
idx1 = [0,4,2]
idx2 = [1,3,5]
print("Print First index:",arr[idx1])
print("Print second index",arr[idx2])

# Boolen masking Condition valus grater than 33 pass. [Filer tha data]

marks = arr > 33
print("Print pass student grater than 33:",arr[marks])

# Boolen masking Condition valus less than 33 fail.
marks = arr < 33
print("Print fail student less than 33:",arr[marks])

Print First index: [50 78 25]
Print second index [30 65 39]
Print pass student grater than 33: [50 65 78 39]
Print fail student less than 33: [30 25]


In [111]:
# Create a 3x3 array filled with random number and print its shape.

arr = np.random.rand(3,3)
print(arr)
print(arr.shape)

[[0.04485921 0.07121072 0.83880727]
 [0.39495446 0.31818897 0.01239771]
 [0.41878187 0.72988971 0.1265075 ]]
(3, 3)


In [120]:
# convert an array of floats [1.1,2.2,3.3,4.4,5.5,6.6,7.7] into integers.

arr = np.array([1.1,2.2,3.3,4.4,5.5,6.6,7.7])
arr_int = arr.astype(int) 
print("Print integers values",arr_int)


arr = np.array([1.1,2.2,3.3,4.4,5.5,6.6,7.7], np.dtype(int))
print("Print integers values",arr)

Print integers values [1 2 3 4 5 6 7]
Print integers values [1 2 3 4 5 6 7]


In [128]:
# convert an array of integer [10,20,11,33,44,21] into float.

arr = np.array([10,20,11,33,44,21], np.dtype(float))
print(arr)


arr = np.array([10,20,11,33,44,21])
arr_float = arr.astype(float)
print("print Float values:",arr_float)

[10. 20. 11. 33. 44. 21.]
print Float values: [10. 20. 11. 33. 44. 21.]


In [142]:
# use fancy indexing to extract even number from [1,2,3,4,5,6,7,8,9]

arr = np.array([1,2,3,4,5,6])
idx = [1,3,5]
print(arr[idx])

[2 4 6]


In [152]:
# reshape a 1D array of size into 3x3 matrix.

arr = np.array([1,2,3,4,5,6,7,8,9])
print("print 1D array:",arr)

matrix = arr.reshape(3,3)
print("Print reshape 2D array",matrix)

print 1D array: [1 2 3 4 5 6 7 8 9]
Print reshape 2D array [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [153]:
# use boolean Masking to filter number greater than 50 in aaray.

arr = np.array([60,20,25,85,55,33,89,98,22,66,77])
marks = arr > 50
print("print number greater than 50:",arr[marks])

print number greater than 50: [60 85 55 89 98 66 77]
