In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5,6])
print(arr)
result = []

for num in arr:
    result.append(num**2)
print(result)

[1 2 3 4 5 6]
[np.int64(1), np.int64(4), np.int64(9), np.int64(16), np.int64(25), np.int64(36)]


In [3]:
# Vectorized Operation.

arr = np.array([1,2,3,4,5,6])
result = arr ** 2
print(result)

[ 1  4  9 16 25 36]


In [4]:
# Broadcasting Scaling Arrays without Extra Memory.

arr = np.array([10,20,30,40,50,60])
result = arr + 12
print(result)

[22 32 42 52 62 72]


In [5]:
# Boardcasting with Two Arrays.

# logic step
arr1 = np.array([10,20,30])
arr2 = np.array([2,4,7])
print(arr1 + arr2)

# more logic step 
arr3 = np.array([2,7,5,3])
arr4 = np.array([5,2,3,8])
result = arr3 * arr4
print(result)

[12 24 37]
[10 14 15 24]


In [6]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
arr1 = arr + ([1,2,3])
print("2D Array sum:",arr1)

[[1 2 3]
 [4 5 6]]
2D Array sum: [[2 4 6]
 [5 7 9]]


In [7]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([10,20,30])
result = arr1 + arr2
print(result)

[[11 22 33]
 [14 25 36]]


In [8]:
# Normalizing Data using Broadcasting.

Data = np.array([[10,20,30],[15,25,35],[20,35,45],[30,40,50]])
print(Data)

mean = Data.mean(axis=0)
std = Data.std(axis=0)

normalized_Data = (Data - mean) / std
print(normalized_Data)

[[10 20 30]
 [15 25 35]
 [20 35 45]
 [30 40 50]]
[[-1.18321596 -1.26491106 -1.26491106]
 [-0.50709255 -0.63245553 -0.63245553]
 [ 0.16903085  0.63245553  0.63245553]
 [ 1.52127766  1.26491106  1.26491106]]
