In [1]:
import numpy as np

In [2]:
# Built  mathematical function in numpy

In [3]:
# 1.mean (average) of an array

# step 1
arr = np.array([10,20,30,40,50])
print(np.mean(arr))
print(arr.dtype)

# step 2
arr = np.array([10,20,30,40,50])
mean = np.mean(arr)
print(mean)

30.0
int64
30.0


In [4]:
# 2.standard deviation of an array.

arr = np.array([70,22,31,48,57])
print(np.std(arr))

arr = np.array([70,22,31,48,57])
std = np.std(arr)
print(std)

17.327434893832383
17.327434893832383


In [5]:
# 3.Minimum value of an array.

arr = np.array([12,100,78,81,20,32])
print(np.min(arr))

arr = np.array([12,100,78,81,20,32])
min = np.min(arr)
print(min)

12
12


In [6]:
# 4. Varience of an array.

arr = np.array([2,5,3,7,8])
print(np.var(arr))

arr = np.array([2,5,3,7,8])
var = np.var(arr)
print(var)

5.2
5.2


In [7]:
# 5.maximum value of an array.

arr = np.array([200,452,985,989,1025])
print(np.max(arr))

arr = np.array([200,452,985,989,1025])
max = np.max(arr)
print(max)

1025
1025


In [8]:
# 6.sum of all elements in the array.

arr = np.array([10,2,30,52,63])
print(np.sum(arr))

arr = np.array([10,2,30,52,63])
sum = np.sum(arr)
print(sum)

157
157


In [9]:
# 7.product of all elements in the array.

arr = np.array([2,4,5,3])
print(np.prod(arr))

arr = np.array([2,4,5,3])
prod = np.prod(arr)
print(prod)

120
120


In [10]:
# 8.Median of an array.

arr = np.array([20,30,40,50,100])
print(np.median(arr))

arr = np.array([20,30,40,50,100])
median = np.median(arr)
print(median)

40.0
40.0


In [11]:
# 9.Percentile of an array.

arr = np.array([20,30,40,50,100])
print(np.percentile(arr,40))

arr = np.array([20,30,40,50,100])
percentile = np.percentile(arr,50)
print(percentile)

36.0
40.0


In [12]:
# 10. argmin index minimum value in an array.

arr = np.array([70,30,40,50,100])
print(np.argmin(arr))

arr = np.array([70,30,40,50,100])
argmin = np.argmin(arr)
print(argmin)

1
1


In [13]:
# 11.argmax index maximum values in array

arr = np.array([70,30,40,50,100])
print(np.argmax(arr))

arr = np.array([70,30,40,50,100])
argmax = np.argmax(arr)
print(argmax)

4
4


In [14]:
#.12 Correcation coefficient matrix of two arrays.

arr1 = np.array([2,3,4,5,6])
arr2 = np.array([5,2,3,4,5])

print(np.corrcoef(arr1,arr2))

[[1.         0.24253563]
 [0.24253563 1.        ]]


In [15]:
# 13. Unique elements of an array.

arr = np.array([12,10,56,14,10,12,32,23,12])
print(np.unique(arr))

arr = np.array([12,10,56,14,10,12,32,23,12])
unique = np.unique(arr)
print(unique)

[10 12 14 23 32 56]
[10 12 14 23 32 56]


In [16]:
# 14. differences of an array.

arr = np.array([10,20,30,25,50])
print(np.diff(arr))

arr = np.array([10,20,30,25,50])
diff = np.diff(arr)
print(diff)

[10 10 -5 25]
[10 10 -5 25]


In [17]:
# 15. cumulative sum of an array.

arr = np.array([10,20,30,40,50])
print(np.cumsum(arr))

arr = np.array([1,2,3,4,5,6])
cumsum = np.cumsum(arr)
print(cumsum)

[ 10  30  60 100 150]
[ 1  3  6 10 15 21]


In [18]:
# 16. evenly spaced numbers over a specified interval.

arr = np.linspace(0,10,5)
print(arr)

[ 0.   2.5  5.   7.5 10. ]
